# Render Blueprint for ChatBot
services:
  # Python Backend Service
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: "*"
