services:
  # Backend API Service
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend.py"
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: "*"

  # Static Site Service for Frontend
  - type: static
    name: chatbot-frontend
    buildCommand: "echo 'No build needed for static files'"
    staticPublishPath: .
    plan: free
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
